### ISSUE TITLE
Possible typo in mblogit code

### ISSUE THREAD

**Issue by DarwinAwardWinner** [melff/mclogit#13]
In the code in mblogit for dealing with the groups argument, there seems to be a typo on [line 124](https://github.com/melff/mclogit/blob/f5ef7282dc5929b58facf299e46519499d73282f/pkg/R/mblogit.R#L124):

    gf <- as.formula(rf)

As far as I can tell, the variable `rf` should never be defined at this point in the code (since it is only defined in a mutually exclusive branch of the if/else), so this line will always throw an error. Presumably the correct line is:

    gf <- as.formula(gf)

**Comment by melff** [comment]
Thans for reporting! Fixed in 6fdf9f78f19d36f129e3e5fbfe54b4953fd35886 (release 0.8.6.4.1).
