### ISSUE TITLE
Error with "predict" command in newest versions

### ISSUE THREAD

**Issue by kaylynsanbower** [melff/mclogit#14]
Hello Prof. Elff, 
I'm using the mclogit command for an analysis and encountered an error with the post estimation command "predict" when using a more recent version of the package. The error reads: 

Error in .TM.repl.i.mat(as(x, "TsparseMatrix"), j=j, value=value) : column indices must be <= ncol(.) which is 1417. 

I'm able to get the predicted choice probabilities with version 0.8.5.1, but the error with the newer version makes me think that there may be a bug. Thanks for all of your work on this package; it's been incredibly useful for me. 
Cheers, 
Kaylyn

**Comment by melff** [comment]
I thought to have fixed this or a similar bug recently with release 0.8.7. Can you confirm that this error shows up with the most recent release?

**Comment by kaylynsanbower** [comment]
Yes, I get this error with version 0.8.6.4. I just re-ran it to double check.

**Comment by melff** [comment]
Can you try again with 0.8.7 (https://github.com/melff/mclogit/releases/tag/0.8.7)?

**Comment by kaylynsanbower** [comment]
With this version, I get a new error in the estimation stage, so I'm not sure what will happen if I try to predict. Here's the error: 

Error in mclogit(cbind(choice, id) ~ rvn_1.25 + treat_1.25 + int_1.25 +  : 
  No predictor variable remains in random part of the model.
Please reconsider your model specification.
In addition: Warning message:
In mclogit(cbind(choice, id) ~ rvn_1.25 + treat_1.25 + int_1.25 +  :
  removing intercept from random part of the model
 because of insufficient within-choice set variance

**Comment by melff** [comment]
It looks as if your independent variables are constant within choice sets. This is what the error message says. Perhaps what you want to do is a baseline logit model. See ?mblogit.

**Comment by kaylynsanbower** [comment]
Good point! I had a mistake in my code to create the data frame that I was working on. I fixed that issue, so now I do have variation across my independent variables within the choice sets and am able to estimate with mclogit now. However, I'm still getting the error with the predict command using version 8.7. (The same error I showed above.)

**Comment by melff** [comment]
Can you send me (an extract of) your data, so that I can debug? Thanks!

**Comment by kaylynsanbower** [comment]
Here’s an extract of the data and an excerpt of the code in case you want to see what I was trying to do when I ran into the error. Thanks!

**Comment by melff** [comment]
Sorry, this didn't work. Please either upload the file via the GitHub interface or send the file to me directly, i.e. martin@elf.eu.

**Comment by melff** [comment]
Fixed in release [0.8.7.1](https://github.com/melff/mclogit/releases/tag/0.8.7.1)

**Comment by kaylynsanbower** [comment]
Works like a charm! Thanks for your responsiveness and your work on this package in general.
