### ISSUE TITLE
`*tmp*`[[k]] : subscript out of bounds

### ISSUE THREAD

**Issue by cxquy91** [melff/mclogit#15]
Dear Dr. Elff,

I was trying to run function mblogit today (version 0.8.7.1) for a multinomial mixed logistic regression model. Here is the code:

mblogit(value ~ Scan_type , random = ~ 1|(Rater2 + Subject_ID), data = final_df)

This model works fine with 1 random intercept (either Rater2 or Subject_ID), but when consider both of them, I have this error after 6 iterations (models converge too!): `*tmp*`[[k]] : subscript out of bounds.

Could you please let me know what I could do to get around this problem?

Thanks,
Quy

**Comment by melff** [comment]
It seems that you are trying to fit a model with crossed random effects. These are not supported yet. It seems I have to document that more clearly.

**Comment by cxquy91** [comment]
I see... Since we can't perform a crossed random effects, would you suggest to treat raters as fixed effect and keep subjects as random effect?
