### ISSUE TITLE
Problems with model definition

### ISSUE THREAD

**Issue by styvens** [melff/mclogit#20]
Thank you, the library has been very useful to me.

My problem is when I want to fit a model from the definition of formula (as.formula ()) and also add random effects:

```r

# this worked
m <-mclogit::mblogit(y ~ x1+x2,random = ~1|id,
                 data = df)

# this did not work
model<-as.formula(y~x1+x2)
m <-mclogit::mblogit(model,random = ~1|id,
                 data = df)

output: Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  cannot set attribute on a symbol

```

The reason to define the model like this is that I am creating a function that calls to mblogit.

Thank you for your time.

**Comment by melff** [comment]
This should be fixed by release 0.8.7.4 (not yet on CRAN). Can you check whether you still have the problem with the current release? Thank you.
