### ISSUE TITLE
mclogit for multinominal logistic regression with fixed effects (conditional multinomial logistic)

### ISSUE THREAD

**Issue by colospring** [melff/mclogit#8]
Hi, may I ask a question on using this package? I need to run a multinomial logistic regression with fixed effects. It seems that this package is the closest to what I want, but I don't know whether it can do this? if it can, then how to add fixed effects? I have read the package instructions but still don't understand it. Thank you very much!

**Comment by melff** [comment]
As you are certainly aware, in the econometrics of panel data, fixed effects are used to deal with heterogeneity between panels without the need to assume that the heterogeity is exogenous. In linear panel models for quantitative responses this can either be done by including group dummies into the model or by subtracting group means from the dependent *and* independent variables.
In models for categorical dependent variables the "trick" of subtracting group means is not available. 

For binary responses an alternative to the use of group dummies is conditional logit modelling (*not* in the sense of conditional logit modelling for discrete choices), however this approach becomes unwieldy with more than three panel waves.

The "conditional logit" models that *mclogit* supports are *not* intended as models for binary responses in panel data or a generalisation thereof, they are rather the conditional logit models for discrete choices introduced by McFadden in 1974.

As far as I understand it, the only way to model fixed effects with polychotomous categorical responses is to fit a model with group dummies. However, this can lead to convergence problems if the number of groups is very large. 

I shall not rule out that there is a polychotomous generalisation of conditional logit models for binary panel data, and it would be great if it could be expressed in terms of discrete choice conditional logit models, but I am currently not aware of it.
